# Generated by Django 5.1.4 on 2024-12-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0006_remove_onlinecourse_sub_category_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(blank=True, help_text='Other batches the student is part of', related_name='students', to='product.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_batch',
            field=models.ForeignKey(blank=True, help_text='The main batch for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_students', to='product.batch'),
        ),
    ]
