# Generated by Django 5.1.4 on 2025-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_batches_student_primary_batch'),
        ('product', '0012_batch_current_students_batch_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='product.onlinecourse'),
        ),
    ]
