# Generated by Django 5.1.4 on 2024-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourse',  # Updated to the correct model
            name='sub_category',
            field=models.CharField(blank=True, choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('vocals', 'Vocals')], max_length=10, null=True),
        ),
    ]
