# Generated by Django 5.1.4 on 2024-12-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0002_offlinecourse_image_onlinecourse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='course',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offline_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.offlinecourse'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.onlinecourse'),
        ),
        migrations.CreateModel(
            name='CartOfflineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.offlinecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='CartOnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.onlinecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
