# Generated by Django 5.1.4 on 2024-12-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_orderitem_course_orderitem_offline_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartofflinecourse',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.batch'),
        ),
    ]
