# Generated by Django 5.1.4 on 2024-12-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_course_sub_category'),
        ('product', '0004_cartofflinecourse_batch'),
    ]

    operations = [
    ]
