# Generated by Django 5.1.4 on 2024-12-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0005_merge_20241212_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinecourse',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.offlinecourse')),
                ('online_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.onlinecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'unique_together': {('student', 'offline_course'), ('student', 'online_course')},
            },
        ),
    ]
