# Generated by Django 5.1.4 on 2025-01-08 05:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_batches_student_primary_batch'),
        ('product', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='account.student'),
        ),
        migrations.AlterField(
            model_name='offlinecourse',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(help_text='Personal notes for the course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_notes', to='product.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_notes', to='product.onlinecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineCourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the content (e.g., Module 1)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for this content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='product.offlinecourse')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='offline_course_files/')),
                ('title', models.CharField(help_text='Title for the file', max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='product.offlinecoursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the content (e.g., Module 1)', max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Optional description for this content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='product.onlinecourse')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='online_course_files/')),
                ('title', models.CharField(help_text='Title for the file', max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='product.onlinecoursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='UploadOfflineCourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content (e.g., Week 1 Material)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the content', null=True)),
                ('file', models.FileField(help_text='Upload content file', upload_to='offline_course_content_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contents', to='product.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contents', to='account.teacher')),
            ],
        ),
    ]
