# Generated by Django 5.1.4 on 2025-01-08 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_faq_announcement_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinecoursecontent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description for this content', null=True),
        ),
        migrations.AlterField(
            model_name='uploadofflinecoursecontent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional description for this content', null=True),
        ),
    ]
