# Generated by Django 5.1.4 on 2025-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_offlinecoursecontent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadofflinecoursecontent',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], default='pdf', help_text='Type of the content file', max_length=10),
        ),
    ]
