# Generated by Django 5.1.4 on 2025-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_uploadofflinecoursecontent_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='current_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='batch',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
